= SpringBoot Templet REST API Guide
Always0ne;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===

[[overview-errors]]
== 오류

에러 응답이 발생했을 때 (상태 코드 >= 400), 본문에 해당 문제를 기술한 JSON 객체가 담겨있다.
[[AuthError]]
=== Auth Error
[[E0001]]
==== Error0001
operation::0001[snippets='response-body']
[[E0002]]
==== Error0002
operation::0002[snippets='response-body']
[[E0003]]
==== Error0003
operation::0003[snippets='response-body']
[[E0004]]
==== Error0004
operation::0004[snippets='response-body']
[[E0005]]
==== Error0005
operation::0005[snippets='response-body']
[[E0006]]
==== Error0006
operation::0006[snippets='response-body']

[[CommunityError]]
=== Community Error
[[E1001]]
==== Error1001
operation::1001[snippets='response-body']

[[PostError]]
==== Post Error
[[E1101]]
===== Error1101
operation::1101[snippets='response-body']

[[CommentError]]
==== Comment Error

[[SystemError]]
=== System Error
[[E2001]]
==== Error2001
operation::2001[snippets='response-body']

[[overview-hypermedia]]
== 하이퍼미디어

본 REST API는 하이퍼미디어와 사용하며 응답에 담겨있는 리소스는 다른 리소스에 대한 링크를 가지고 있다.
응답은 http://stateless.co/hal_specification.html[Hypertext Application from resource to resource. Language (HAL)] 형식을 따른다.
링크는 `_links`라는 키로 제공한다. 본 API의 사용자(클라이언트)는 URI를 직접 생성하지 않아야 하며, 리소스에서 제공하는 링크를 사용해야 한다.

[[signin]]
=== 인증하기

`Post` 요청을 사용해서 인증할수있다.

operation::signin[snippets='http-request,http-response']

[[signup]]
=== 회원가입하기

`Post` 요청을 사용해서 회원가입을 할 수있다.

operation::signup[snippets='http-request,http-response']

[[checkid]]
=== 회원가입하기

`Get` 요청을 사용해서 아이디 중복확인을 할 수있다.

operation::idcheck[snippets='http-request,http-response']

[[getPosts]]
=== 게시글 목록 조회

`Get` 요청을 사용해서 게시글 목록을 조회 할 수 있다.

operation::getPosts[snippets='http-request,http-response']

[[sendPost]]
=== 게시글 작성

`Post` 요청을 사용해서 게시글을 작성 할 수 있다.

operation::sendPost[snippets='http-request,http-response']

[[getPost]]
=== 게시글 조회

`Get` 요청을 사용해서 게시글을 조회 할 수 있다.

operation::getPost[snippets='path-parameters,http-request,http-response']

[[updatePost]]
=== 게시글 수정

`Put` 요청을 사용해서 게시글을 수정 할 수 있다.

operation::updatePost[snippets='path-parameters,http-request,http-response']

[[deletePost]]
=== 게시글 삭제

`Delete` 요청을 사용해서 게시글을 삭제 할 수 있다.

operation::deletePost[snippets='path-parameters,http-request,http-response']

[[sendComment]]
=== 댓글 작성

`Post` 요청을 사용해서 댓글을 작성 할 수 있다.

operation::sendComment[snippets='path-parameters,http-request,http-response']

[[updateComment]]
=== 댓글 수정

`Put` 요청을 사용해서 댓글을 수정 할 수 있다.

operation::updateComment[snippets='path-parameters,http-request,http-response']

[[deleteComment]]
=== 댓글 삭제

`Delete` 요청을 사용해서 댓글을 삭제 할 수 있다.

operation::deleteComment[snippets='path-parameters,http-request,http-response']
